### PR TITLE
Get involved page

### PR DESCRIPTION
**Pull request by smunson**
Let's try this

### CODE REVIEW

**Comment by jayfo** [comment]
Pushed some edits on "Getting Involved", I think it's good, maybe check it out.

I will plan to make some corresponding edits to "Coordinators", then merge this.  Fixing the CSS will follow.

**Comment by andyjko** [comment]
The new content in Getting Involved is great. I've found that prospectives read these pages pretty closely, so it doesn't matter too much how far down the page anything is.

**Comment by smunson** [comment]
Yeah, this will be super-useful to have online and no objections to the edits. Thanks!

**Comment by jayfo** [comment]
Rebased and merged this.

Please eyeball it on the web, checking for typos or changes we should make.

I'll take a pass over the CSS styling when I get a chance, but it's tolerable for now.

**Pull request merged**
