### PR TITLE
relieving myself of responsibility

### PR DESCRIPTION
**Pull request by smunson**
also updated student coordinators and a typo

### CODE REVIEW

**Comment by depstein** [comment]
Two typos in the edits: Shefali Haldar, Audrey Desjardins

**Comment by smunson** [comment]
thanks; that's what I get for doing things as I walk out of a meeting.

**Comment by depstein** [comment]
That's how Eunice Junice sticks around for so long :-D

**Comment by smunson** [comment]
it's kind of catchy, Daniel Epstiel.

**Pull request merged**
