### PR TITLE
Updated community day agenda.

### PR DESCRIPTION
**Pull request by amyjko**
A few tweaks and additional details to the community day agenda.

### CODE REVIEW

**Review by jayfo — COMMENTED** [review]
Is keynote 2 also supposed by be hybrid?

**Review by jayfo — COMMENTED** [review]
I will also reformat times again before merging (e.g., 0150-0200 will become 1:50-2:00), because blah blah consistent blah blah rest of site.

I'm fine with that, or you could do that too.

**Comment by amyjko** [comment]
Thanks! Fixed the hybrid label and time formats.

**Review by amyjko — COMMENTED** [review]
Added more agenda details.

**Pull request merged**
